#!/usr/bin/env bash
echo Updating pip and related modules...
pip install --upgrade pip wheel build setuptools twine

echo Updating essentials...
pip install --upgrade flake8 requests tqdm youtube-dl pytest

echo Done...
