/*
 * Problem 2: Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four
 * million, find the sum of the even-valued terms.
 *
 * https://projecteuler.net/problem=2
 */

#include <stdio.h>

int evenFibonacciNumbers(int x, int y, int sequence_sum)
{
    if (y >= 4000000)  // Only evaluate values less than 4,000,000.
    {
        return sequence_sum;
    }
    else
    {
        int z = x + y;  // Get the next value of the fibonacci sequence.
        if (z % 2 == 0)
        {
            sequence_sum += z;
        }

        return evenFibonacciNumbers(y, z, sequence_sum);
    }
}

int main()
{
    // Give the default values of x, y, and sequence_sum.
    // sequence_sum is already at value 2 because `y` (an even number)
    // will not be evaluated by the function, resulting to a value two
    // less than the expected output.
    printf("%d\n", evenFibonacciNumbers(1, 2, 2));
    return 0;
}
