--[[
Problem #2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terns will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2
--]]

function evenFibonacciNumbers(x, y, sequence_sum)
    local z = x + y  -- Get the next number in the sequence.
    if z >= 4000000 then  -- Evaluate numbers less than 4,000,000 only.
        return sequence_sum
    end

    if z % 2 == 0 then  -- Add to sum if z is even.
        sequence_sum = sequence_sum + z
    end

    return evenFibonacciNumbers(y, z, sequence_sum)
end

function main()
    print(evenFibonacciNumbers(1, 2, 2))
end

main()

